import React from "react";
import page from "./page";
import "./globals.css";
import { ReactDOM } from "react-dom/client";
import { Navbar } from "./components/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

function layout() {
  return (
    <div>
      <Navbar />
      <RootLayout />
    </div>
  );
}
